default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: event_user
  password: 123456
  encoding: utf8
  host: 127.0.0.1

development:
  <<: *default
  database: store_rb

# test:
#   <<: *default
#   database: store_rb

production:
  <<: *default
  database: store_rb
